### ISSUE TITLE
zprint COS command does not work

### ISSUE THREAD

**Issue by yaronmunz** [intersystems-community/webterminal#125]
I have installed WebTerminal on IRIS 2019.1.0 and it is working great.
However, a ZP (zprint) COS command does not work.
when issuing for example:
zl test zp
I get the USER> prompt without anything
(if issuing the same on IRIS terminal, all work fine... i.e the routine has a source).

I have seen that the ZP (zprint) command is missing on the StaticContent class.
I tried to add it there, and then autocomplete of ZP (to zprint) works, but still not output is sent back to the client.

**Comment by ZitRos** [comment]
Hello @yaronmunz! Thank you for reporting this issue.

The thing is, we have a [group of issues](https://github.com/intersystems-community/webterminal/issues?q=is%3Aissue+is%3Aopen+label%3A%22Core+Enhancement+%28blocker%29%22) labeled `Core Enhancement (blocker)`, which doesn't allow to run something exactly because of how WebTerminal works under the hood (on top of ObjectScript `xecute` + I/O redirection). Some system routines have their own rules for input/output (they switch output devices or expect some core terminal/system variables to be set by underlying I/O system), hence new problems appear.

I assume this wouldn't be the case if I implemented, for example, WebTerminal over [telnet](https://github.com/intersystems-community/webterminal/issues/103) (because telnet wraps all internal execution magic and works exactly like a terminal), but it seems that this approach also has its own problems. Looks like telnet has its own disadvantages (is it Windows-only?).

So, currently, I am looking for an approach to change WebTerminal's core, which I belive will fix all similar issues, including yours.

**Comment by yaronmunz** [comment]
Hello,

Thank you for your email. I have actually looked into the code. This is a nice implementation of WebSockets.
I think that if you going to use a telnet (stream) object to handle all communication, it might be slower (in response) than the current response time with websocket.

However, I think that some of the issues that were reported (I looked at some of them in github) might be solved with minimal coding of those special cases. (probably the same way you implement the sql feature).

The command ZP (zprint) should not be an issue to use for example:
Set routine = ##class(%Routine).%New("test.int")
while 'routine.AtEnd { w !,routine.ReadLine() }



Yaron Munz
IRIS / Ensemble architect

MSC MEDITERRANEAN SHIPPING COMPANY SA
16, Avenue Eugène Pittard , 1206 Geneva, Switzerland
M: +41 78 721 6666 W: www.msc.com<http://www.msc.com/>

**Comment by ZitRos** [comment]
> However, I think that some of the issues that were reported (I looked at some of them in github) might be solved with minimal coding of those special cases. (probably the same way you implement the sql feature).

Do you mean just hard-coding some cases like "if command = _this_ then execute this custom code"? If so, this is a very dangerous way to fix things... At least, it hides an original behavior from the user, which may mislead them if the command has some options not covered by this "dirty fix".

**Comment by yaronmunz** [comment]
Hello Nikita.

Yes, I agree that  hard coding is "dangerous" and not the proper way to keep everything seamless.

However, the "zl routine zp" command is a very special case that is always done without anything else at that line.. so, I have hard coded that :

[cid:image001.png@01D52FF6.F110FBA0]

Yaron Munz
IRIS / Ensemble architect

MSC MEDITERRANEAN SHIPPING COMPANY SA
16, Avenue Eugène Pittard , 1206 Geneva, Switzerland
M: +41 78 721 6666 W: www.msc.com<http://www.msc.com/>

**Comment by ZitRos** [comment]
I understand this case. However, I would keep hard-coding away from the "official" releases. Just another possible case from numerous cases... If the project goes wild (for example, a maintainer changes) then people will start to hard-code everything by example, and this will turn into a total mess.

I am closing this issue - please feel free follow WebTerminal project, I think it has a good chance to be fixed one day in the future, within the core patch making it 100% compatible with standard Cache Term.
