### ISSUE TITLE
How to debug 'break' in .mac .cls use WebTerminal like Terminal ?

### ISSUE THREAD

**Issue by fdd371github** [intersystems-community/webterminal#134]
How to debug 'break' in .mac .cls use WebTerminal  like Terminal ?

**Comment by ZitRos** [comment]
Hello! Simple answer - unfortunately, traditional debugging is not yet supported in WebTerminal.

Because of the way how WebTerminal was implemented, it is not using a terminal i/o device as well as missing some of its capabilities. It requires re-writing (but at first, figuring out how to do it which is not yet clear) the underlying WebTerminal core (related #103) to make it implemented **over** the traditional terminal, but not **re-implementing** it like it's done right now.
