### ISSUE TITLE
Implemented LDAP Authentication, Can't log on

### ISSUE THREAD

**Issue by DodgeDeBoulet** [intersystems-community/webterminal#139]
IRIS for Health 2020.1, RedHat Linux

WebTerminal was installed and working. In mid-July, we enabled LDAP authentication for the server. At some point during the configuration of LDAP WebTerminal stopped working.

Once user and password are entered, the screen goes black, "Terminal load complete. Getting auth key" flashes very briefly, and then the error "WebTerminal lost connection with server (code 1006).Attempting to restore session in 10 seconds..." displays and repeats periodically.

I believe it is LDAP related because the audit log shows LoginFailure entries for /terminalsocket, with the following error info:

Error message: ERROR #978: System requires that the user must own the IntAnalyst role to connect
Web Application: /terminalsocket
$I: |TCP|51773|19236
$P: |TCP|51773|19236

The user signing onto WebTerminal has the IntAnalyst role.

**Comment by ZitRos** [comment]
Hello!

Interesting. I've never tried enabling LDAP, maybe someone else can hint or help to identify why does it impact the web application authentication (@eduard93 @evshvarov).

From the WebTerminal standpoint, the default CSP authentication is used in its web applications (`/terminal`, `/terminalsocket`), and then the terminal transfers some security keys over the established connection (which is not the issue as far as I can see).

**Comment by DodgeDeBoulet** [comment]
I've been able to get it to work with the following settings:

* Add LDAP authentication to web service **/terminal**
* Have Unauthenticated and LDAP security enabled for **/terminalsocket**
* Remove the value in "Role required to connect to this system" from System-wide Security Parameters (**not** desirable)

**Comment by ZitRos** [comment]
Thanks for investigating it! Glad to hear it works now.

Apart from,

> Remove the value in "Role required to connect to this system" from System-wide Security Parameters (not desirable)

everything is expected. I recall that for WebTerminal to work since 2017-2019 Cache/IRIS versions, the WebSocker connection was refactored to use "Unauthenticated", because otherwise it didn't work at all. However, leaving `/terminalsocket` Unauthenticated has no harm on the security, as the WebSocket connection to this web app closes immediately if it doesn't receive the desired security key, which can be obtained only after authenticating to `/terminal`.
