### ISSUE TITLE
PRA for Wt

### ISSUE THREAD

**Issue by eduard93** [intersystems-community/webterminal#78]
1. Working sample PRA.xml. Requirements:
Users PRAUser1 and PRAUser2 have PRAUser1Role
Role PRAUser1Role has resources %DB_USER:RW and %Development:U and PRATestResource:U
PRA named PRATest requires PRATestResource resource, Application roles = %DB_CACHESYS, Classes: Database - USER, Class - PRA.PRA

2. PRA for wt (In WTPRA.xml).
Users PRAUser1 and UnknownUser have PRAUser1Role
Role PRAUser1Role has resources %DB_USER:RW and %Development:U and PRATestResource:U
PRA named PRATest requires PRATestResource resource, Application roles = %DB_CACHESYS, Classes: Database - USER, Class - WebTerminal.PRA

Expected behavior: successful login, `zn "%SYS"` causes exception.
Real behavior:  successful login, `zn "%SYS"`completes successfully.

[Files](https://github.com/intersystems-ru/webterminal/files/716827/Desktop.zip)

**Comment by eduard93** [comment]
Questions: 
- is it possible to configure PRA for WT, if so, how?
- what is the reason for ability to access %SYS after rpa.

Notes: can't new $roles in rpa or login reverts.

**Comment by eduard93** [comment]
Investigation today yielded no definite results. I'll try tomorrow on a clean instance.

**Comment by ZitRos** [comment]
> Have wt user with no access to %SYS.

I really cannot understand what this means in your context, as if user does not have %DB_CACHESYS or %All roles it won't be able to access %SYS namespace. If it has %DB_USER role, it will be able to access USER database. Can you describe the goal more clearly please?

For example, I have user Nikita with the only one role assigned to him: %DB_USER. During the start, it log ins perfectly fine and cannot zn to the %SYS namespace.

Regarding to PRA demo, I see

```
<PROTECT>zRequireAuthorization+48^WebTerminal.Engine.1 ^dbg(9),c:\program files\intersystems\ensemble\mgr\
```

Error ;)

Use better `do ..Send("o", "any debug info")` instead of `set ^dbg(...) = ...` method to send all the debug information to the web terminal output.

**Comment by ZitRos** [comment]
The idea is that Caché WebTerminal classes, all, except `WebTerminal.Core` class are privileged. The user works in jobbed process, which starts [here](https://github.com/intersystems-ru/webterminal/blob/master/src/cls/WebTerminal/Engine.cls#L158), and once it appears there, it has all the freedom allowed to this user **inside jobbed process**.

**Comment by ZitRos** [comment]
Hi @eduard93,

Is this things still actual?

**Comment by ZitRos** [comment]
Closed due to inactivity.
