### ISSUE TITLE
Don't show suggestions after right parenthesis in the end of the method call 

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/webterminal#94]
if you type 
d ##class(package.class).method()

webterm shows ",##class" at the end. Every time. I didn't use it ever.
Can I turn off it? Or maybe don't show it at all?

Example:
<img width="593" alt="2017-02-13 13 22 26" src="https://cloud.githubusercontent.com/assets/2781759/22896986/f954a8b2-f1ef-11e6-8171-0e13a22cd7a3.png">

**Comment by ZitRos** [comment]
This need a change in autocomplete mechanism, thanks. With the current grammar structure it's hard to determine this case, because autocomplete for, for example, "##class" needs to go through "#" "#" "class" keyword in grammar, as same as for "," "#" "#" "class" (it cannot determine where to stop, it just picks all the variants ahead).

Once I will touch autocomplete mechanism in WebTerminal, I will definitely consider this for the fix.

**Comment by evshvarov** [comment]
Happy to see that, thank you, Nikita!
